envname: SuperMarioBros-1-1-v0
run_name: SuperMarioBrosNes_v0_Stage1
seed: 1
gradientSteps: 80000
replayRatio: 1
saveMetrics: True
saveCheckpoints: True
checkpointInterval: 10
checkpointLoad: 50k
resume: True
use_foveation: False
episodedbeforestart: 10
numInteractionEpisode: 1
numEvaluationEpisode: 1
dreamer:
    batchsize: 32
    batchlength: 64
    imaginehorizon: 30
    recurrentSize: 512
    latentlength: 32
    latentclasses: 16
    encodedObjSize: 1024
    useContinuationPred: False
    actorLR: 0.00007
    criticLR: 0.0001
    worldmodelLR: 0.0002
    gradientNormType: 2
    gradientClip: 10
    discount: 0.996
    lambda_: 0.95
    freeNats: 0.5
    betaPrior: 1.5
    betaPosterior: 1.5
    entropyScale: 0.0005
    buffer:
        capacity: 50000
    encoder:
        depth: 16
        stride: 2
        kernelSize: 4
        activation: ELU
    decoder:
        depth: 16
        stride: 2
        kernelSize: 4
        activation: ELU
    recurrentModel:
        hiddenSize: 200
        activation: ELU
    priorModel:
        hiddenSize: 200
        hiddenLayers: 3
        activation: ELU
        uniformMix: 0.01
    posterior:
        hiddenSize: 200
        hiddenLayers: 3
        activation: ELU
        uniformMix: 0.01
    rewardModel:
        hiddenSize: 400
        hiddenLayers: 3
        activation: ELU
    continuationModel:
        hiddenSize: 400
        hiddenLayers: 3
        activation: ELU
    actorModel:
        hiddenSize: 400
        hiddenLayers: 3
        tau: 1
        activation: ELU
    criticModel:
        hiddenSize: 400
        hiddenLayers: 3
        activation: ELU
folderName:
    metricFolder: metrics
    plotsfolder: plots
    checkpointFolder: checkpoints
    videoFolder: videos
