envname: SuperMarioBros-v0
run_name: SuperMarioBrosNes
seed: 1

gradientSteps: 80000
replayRatio: 1
saveMetrics: True
saveCheckpoints: True
checkpointInterval: 10
resume: False

use_foveation: False
episodedbeforestart: 15
numInteractionEpisode: 3
numEvaluationEpisode: 1

dreamer:
    batchsize: 32
    batchlength: 64
    imaginehorizon: 50      # <--- CRITICAL: 3.3 seconds of foresight to "see" the flagpole

    recurrentSize: 512
    latentlength: 32        # High resolution for complex levels
    latentclasses: 16
    encodedObjSize: 1024

    useContinuationPred: False
    actorLR: 0.0001
    criticLR: 0.0001        # Balanced with Actor
    worldmodelLR: 0.0002
    gradientNormType: 2
    gradientClip: 10

    discount: 0.996
    lambda_: 0.95
    freeNats: 0.01          # <--- FIX: Forces gradients even for small errors
    betaPrior: 1.0          # Balanced pressure
    betaPosterior: 1.0
    entropyScale: 0.005     # <--- TWEAK: Less jitter, more "committed" jumps

    buffer:
        capacity: 50000

    encoder:
        depth: 16
        stride: 2
        kernelSize: 4
        activation: ELU

    decoder:
        depth: 16
        stride: 2
        kernelSize: 4
        activation: ELU

    recurrentModel:
        hiddenSize: 400      # <--- BUFF: Need more power to process 32x16 latents
        activation: ELU

    priorModel:
        hiddenSize: 400
        hiddenLayers: 2
        activation: ELU
        uniformMix: 0.01

    posterior:
        hiddenSize: 400
        hiddenLayers: 2
        activation: ELU
        uniformMix: 0.01

    rewardModel:
        hiddenSize: 400
        hiddenLayers: 2
        activation: ELU

    continuationModel:
        hiddenSize: 400
        hiddenLayers: 3
        activation: ELU

    actorModel:
        hiddenSize: 400
        hiddenLayers: 2
        tau: 1.0
        activation: ELU

    criticModel:
        hiddenSize: 400
        hiddenLayers: 3
        activation: ELU

folderName:
    metricFolder: metrics
    plotsfolder: plots
    checkpointFolder: checkpoints
    videoFolder: videos
